import type { Metadata } from "next";
import "./globals.css";
import Gnb from "@components/common/Gnb";
import ReactQueryProvider from "@providers/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-gray-100 font-pretendard antialiased">
        <ReactQueryProvider>
          <Gnb />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
